### ISSUE TITLE
It is possible to open the modal centered vertically?

### ISSUE THREAD

**Issue by jonagoldman** [samdark/the-modal#46]
I want to be able to open the modal vertically centered in the middle of the page.
Setting a fixed top margin in the css (margin:20px auto) seems a bit restrictive.
Thanks

**Comment by HelgaZhizhka** [comment]
@samdark  , thank you very much for this plugin. I've been looking for such a solution for the modal window. For centered vertically we can use flexbox , but if you not require support for older browsers 
https://jsfiddle.net/helgaj/7xoez8ve/ 
I use this solution for own projects

**Comment by samdark** [comment]
Overall, since it's possible to achieve with CSS, I think no changes are required in the plugin itself so closing the issue.
