### ISSUE TITLE
Publish the-modal on npm

### ISSUE THREAD

**Issue by bingocaller** [samdark/the-modal#61]
Hi @samdark,

Would it be possible to publish the-modal on npm as well as on bower ([npmjs.com/package/the-modal](https://www.npmjs.com/package/the-modal) is free!)?
We're currently using it in our project, and we'd like to switch to only using `npm` for dependency management.

Thanks in advance! :)

**Comment by samdark** [comment]
Yes.

**Comment by samdark** [comment]
https://www.npmjs.com/package/the-modal

**Comment by bingocaller** [comment]
U DA REAL MVP @samdark! 💯
